from os import system

lib_list = ['libopencv_reg.3.1.dylib','libopencv_surface_matching.3.1.dylib','libopencv_dnn.3.1.dylib','libopencv_superres.3.1.dylib','libopencv_xobjdetect.3.1.dylib','libopencv_xphoto.3.1.dylib','libopencv_bgsegm.3.1.dylib','libopencv_bioinspired.3.1.dylib','libopencv_dpm.3.1.dylib','libopencv_line_descriptor.3.1.dylib','libopencv_saliency.3.1.dylib','libopencv_ccalib.3.1.dylib','libopencv_rgbd.3.1.dylib','libopencv_tracking.3.1.dylib','libopencv_videostab.3.1.dylib','libopencv_aruco.3.1.dylib','libopencv_optflow.3.1.dylib','libopencv_stitching.3.1.dylib','libopencv_datasets.3.1.dylib','libopencv_face.3.1.dylib','libopencv_text.3.1.dylib','libopencv_photo.3.1.dylib','libopencv_ximgproc.3.1.dylib','libopencv_objdetect.3.1.dylib','libopencv_xfeatures2d.3.1.dylib','libopencv_shape.3.1.dylib','libopencv_video.3.1.dylib','libopencv_calib3d.3.1.dylib','libopencv_features2d.3.1.dylib','libopencv_flann.3.1.dylib','libopencv_ml.3.1.dylib','libopencv_highgui.3.1.dylib','libopencv_videoio.3.1.dylib','libopencv_imgcodecs.3.1.dylib','libopencv_imgproc.3.1.dylib','libopencv_core.3.1.dylib']
libs_list = ['/Library/Python/2.7/site-packages/cv2.so','/usr/local/lib/libopencv_reg.3.1.dylib','/usr/local/lib/libopencv_surface_matching.3.1.dylib','/usr/local/lib/libopencv_dnn.3.1.dylib','/usr/local/lib/libopencv_superres.3.1.dylib','/usr/local/lib/libopencv_xobjdetect.3.1.dylib','/usr/local/lib/libopencv_xphoto.3.1.dylib','/usr/local/lib/libopencv_bgsegm.3.1.dylib','/usr/local/lib/libopencv_bioinspired.3.1.dylib','/usr/local/lib/libopencv_dpm.3.1.dylib','/usr/local/lib/libopencv_line_descriptor.3.1.dylib','/usr/local/lib/libopencv_saliency.3.1.dylib','/usr/local/lib/libopencv_ccalib.3.1.dylib','/usr/local/lib/libopencv_rgbd.3.1.dylib','/usr/local/lib/libopencv_tracking.3.1.dylib','/usr/local/lib/libopencv_videostab.3.1.dylib','/usr/local/lib/libopencv_aruco.3.1.dylib','/usr/local/lib/libopencv_optflow.3.1.dylib','/usr/local/lib/libopencv_stitching.3.1.dylib','/usr/local/lib/libopencv_datasets.3.1.dylib','/usr/local/lib/libopencv_face.3.1.dylib','/usr/local/lib/libopencv_text.3.1.dylib','/usr/local/lib/libopencv_photo.3.1.dylib','/usr/local/lib/libopencv_ximgproc.3.1.dylib','/usr/local/lib/libopencv_objdetect.3.1.dylib','/usr/local/lib/libopencv_xfeatures2d.3.1.dylib','/usr/local/lib/libopencv_shape.3.1.dylib','/usr/local/lib/libopencv_video.3.1.dylib','/usr/local/lib/libopencv_calib3d.3.1.dylib','/usr/local/lib/libopencv_features2d.3.1.dylib','/usr/local/lib/libopencv_flann.3.1.dylib','/usr/local/lib/libopencv_ml.3.1.dylib','/usr/local/lib/libopencv_highgui.3.1.dylib','/usr/local/lib/libopencv_videoio.3.1.dylib','/usr/local/lib/libopencv_imgcodecs.3.1.dylib','/usr/local/lib/libopencv_imgproc.3.1.dylib','/usr/local/lib/libopencv_core.3.1.dylib']
cmd = 'install_name_tool -change '
path = '/usr/local/lib/'

for item in lib_list:
	for lib in libs_list:
		system(cmd + 'lib/' + item + ' ' + path + item + ' ' + lib)
